update repos and create new commands to create fresh instances
ct-fiuba/contact-tracing pull request #7
Opened 2020-12-08 22:08 UTC by tomasaccini

Armé un docker-compose nuevo que usa una base de datos no persistente, y agregué nuevos comandos al makefile para poder levantar y tirar estas imagenes.

```
taccini@taccini-mbp contact-tracing % make run-fresh                           <---------------------
./run-fresh.sh -b
Running... 'docker-compose -f docker-compose.fresh.yml up --build'
Creating network "contact-tracing_access-network" with the default driver
Creating network "contact-tracing_internal-network" with the default driver
WARNING: Found orphan containers (contact-tracing_web-app_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Building user-api
Step 1/8 : FROM node:12.4.0
 ---> b074182f4154
Step 2/8 : WORKDIR /app
 ---> Using cache
 ---> 27aa0b6f173e
Step 3/8 : COPY package.json ./
 ---> Using cache
 ---> 08366bf93ba1
Step 4/8 : RUN npm install
 ---> Using cache
 ---> 574626944d12
Step 5/8 : COPY main.js .
 ---> Using cache
 ---> a12f5782f57b
Step 6/8 : COPY src/ src/
 ---> Using cache
 ---> b893bf8d327d
Step 7/8 : EXPOSE 5000
 ---> Using cache
 ---> d4cb87fcd3d2
Step 8/8 : ENTRYPOINT [ "npm", "start" ]
 ---> Using cache
 ---> 767908452255
Successfully built 767908452255
Successfully tagged ct-user-api:latest
Building visit-manager
Step 1/8 : FROM node:12.4.0
 ---> b074182f4154
Step 2/8 : WORKDIR /app
 ---> Using cache
 ---> 27aa0b6f173e
Step 3/8 : COPY package.json .
 ---> Using cache
 ---> 583e08a534a0
Step 4/8 : RUN npm install
 ---> Using cache
 ---> b0fcb4490f79
Step 5/8 : COPY main.js .
 ---> Using cache
 ---> 00ec8bed59e8
Step 6/8 : COPY src/ src/
 ---> Using cache
 ---> 499e9ec453c7
Step 7/8 : EXPOSE 5005
 ---> Using cache
 ---> 4493099cde71
Step 8/8 : ENTRYPOINT [ "npm", "start" ]
 ---> Using cache
 ---> dfe780994977
Successfully built dfe780994977
Successfully tagged ct-visit-manager:latest
Creating contact-tracing_user-api_1                 ... done
Creating contact-tracing_contact-tracing-db-fresh_1 ... done
Creating contact-tracing_visit-manager_1            ... done
taccini@taccini-mbp contact-tracing % make stop-fresh                          <---------------------
docker-compose -f docker-compose.fresh.yml down
Stopping contact-tracing_visit-manager_1            ... done
Stopping contact-tracing_user-api_1                 ... done
Stopping contact-tracing_contact-tracing-db-fresh_1 ... done
WARNING: Found orphan containers (contact-tracing_web-app_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Removing contact-tracing_visit-manager_1            ... done
Removing contact-tracing_user-api_1                 ... done
Removing contact-tracing_contact-tracing-db-fresh_1 ... done
Removing network contact-tracing_access-network
Removing network contact-tracing_internal-network
```

2020-12-09 03:38 UTC, NachoRaik requested changes
LGTM! 2 comments nomas:

- Veria de agregar, ya que esta el PR, el submodule del builder asi ya queda aca.
- Voy a ver si encuentro alguna forma de reutilizar el docker-compose para evitar tener 2 y tener que mantener los 2 synceados. Pero igual si no, me parece que va bien la solución.

2020-12-09 03:38 UTC, NachoRaik commented on docker-compose.fresh.yml
> +      - MONGODB_URI=mongodb://contact-tracing-db-fresh:27017/contact-tracing-db
```suggestion
      - MONGODB_URI=mongodb://contact-tracing-db-fresh:27017/contact-tracing-db-fresh
```

2020-12-09 03:38 UTC, NachoRaik commented on run-fresh.sh
> +docker-compose -f docker-compose.fresh.yml up -d $BUILD_OPTION
Aca no da llamar al builder? O capaz que su llamada dependa de un flag.

2020-12-09 12:14 UTC, olifer97 commented on docker-compose.fresh.yml
> +      - MONGODB_URI=mongodb://contact-tracing-db-fresh:27017/contact-tracing-db
Lo unico que cambia entre los 2 envs es la uri de la db? No se puede hacer con una variable de entorno eso?

2020-12-09 12:15 UTC, olifer97 approved these changes

2020-12-09 20:19 UTC, tomasaccini commented on docker-compose.fresh.yml
> +      - MONGODB_URI=mongodb://contact-tracing-db-fresh:27017/contact-tracing-db
Anduve investigando un poco como se suele hacer esto en docker y parecería que la buena práctica es armar diferentes archivos y poder ir combinandolos, y no recomendaban tanto la generación dinámica de los docker-compose. https://docs.docker.com/compose/extends/

2020-12-09 20:20 UTC, tomasaccini commented on run-fresh.sh
> +docker-compose -f docker-compose.fresh.yml up -d $BUILD_OPTION
Ahí lo agregué :) Si no se pasan los flags directamente se hace la validación en el environment builder

2020-12-22 22:26 UTC, NachoRaik approved these changes
Divino

2020-12-22 22:37 UTC, merged